application: wordpress2blogger
version: 1
runtime: python
api_version: 1

handlers:
- url: /wp2b/.*
  script: wordpress2blogger.py

- url: /
  static_files: static/index.html
  upload: static/.*

- url: /(.*\.(png|html))
  static_files: static/\1
  upload: static/(.*\.(png|html))

