application: livejournal2blogger
version: 1
runtime: python
api_version: 1

handlers:
- url: /lj2b/.*
  script: livejournal2blogger.py
  secure: always

- url: /
  static_files: static/index.html
  upload: static/.*
  secure: always

- url: /(.*\.(png|html))
  static_files: static/\1
  upload: static/(.*\.(png|html))

